services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=statslog"
      - "POSTGRES_PASSWORD=randompassword"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
